"use client";

import { useState } from "react";
import {
  Link2,
  Copy,
  Check,
  Loader2,
  MessageCircle,
  Send,
  Mail,
  ExternalLink,
} from "lucide-react";
import { Button } from "@/components/ui/button";
import {
  Popover,
  PopoverContent,
  PopoverTrigger,
} from "@/components/ui/popover";

interface ShareableLinkButtonProps {
  reportType: "contract" | "offer";
  reportData: any;
  variant?: "default" | "compact";
}

export function ShareableLinkButton({
  reportType,
  reportData,
  variant = "default"
}: ShareableLinkButtonProps) {
  const [isOpen, setIsOpen] = useState(false);
  const [isGenerating, setIsGenerating] = useState(false);
  const [shareUrl, setShareUrl] = useState<string | null>(null);
  const [expiresAt, setExpiresAt] = useState<string | null>(null);
  const [copied, setCopied] = useState(false);
  const [error, setError] = useState<string | null>(null);

  const generateShareableLink = async () => {
    if (shareUrl) return; // Already generated

    setIsGenerating(true);
    setError(null);

    try {
      const response = await fetch("/api/share-report", {
        method: "POST",
        headers: {
          "Content-Type": "application/json",
        },
        body: JSON.stringify({
          reportType,
          reportData,
        }),
      });

      const data = await response.json();

      if (!response.ok) {
        throw new Error(data.error || "Failed to generate link");
      }

      setShareUrl(data.url);
      setExpiresAt(data.expiresAt);
    } catch (err) {
      setError(err instanceof Error ? err.message : "Failed to generate link");
    } finally {
      setIsGenerating(false);
    }
  };

  const handleCopyLink = async () => {
    if (!shareUrl) return;

    try {
      await navigator.clipboard.writeText(shareUrl);
      setCopied(true);
      setTimeout(() => setCopied(false), 2000);
    } catch {
      // Fallback for older browsers
      const textArea = document.createElement("textarea");
      textArea.value = shareUrl;
      document.body.appendChild(textArea);
      textArea.select();
      document.execCommand("copy");
      document.body.removeChild(textArea);
      setCopied(true);
      setTimeout(() => setCopied(false), 2000);
    }
  };

  const shareViaWhatsApp = () => {
    if (!shareUrl) return;
    const text = `Check out this legal document analysis from REXI:\n${shareUrl}`;
    window.open(`https://wa.me/?text=${encodeURIComponent(text)}`, "_blank");
  };

  const shareViaTelegram = () => {
    if (!shareUrl) return;
    const text = `Check out this legal document analysis from REXI`;
    window.open(
      `https://t.me/share/url?url=${encodeURIComponent(shareUrl)}&text=${encodeURIComponent(text)}`,
      "_blank"
    );
  };

  const shareViaEmail = () => {
    if (!shareUrl) return;
    const subject = `REXI Legal Analysis Report`;
    const body = `I wanted to share this legal document analysis with you:\n\n${shareUrl}\n\nGenerated by REXI - Smart Legal Document Review`;
    window.location.href = `mailto:?subject=${encodeURIComponent(subject)}&body=${encodeURIComponent(body)}`;
  };

  const formatExpiryDate = (dateString: string) => {
    return new Date(dateString).toLocaleDateString("en-IN", {
      dateStyle: "medium",
    });
  };

  const handleOpenPopover = (open: boolean) => {
    setIsOpen(open);
    if (open && !shareUrl) {
      generateShareableLink();
    }
  };

  if (variant === "compact") {
    return (
      <Popover open={isOpen} onOpenChange={handleOpenPopover}>
        <PopoverTrigger asChild>
          <button
            className="flex items-center gap-1.5 px-2 py-1 text-xs font-medium text-indigo-600 hover:text-indigo-700 hover:bg-indigo-50 rounded-lg transition-colors"
            title="Get shareable link"
          >
            <Link2 className="w-3.5 h-3.5" />
            <span>Link</span>
          </button>
        </PopoverTrigger>
        <PopoverContent className="w-72 p-3" align="end">
          <ShareableLinkContent
            isGenerating={isGenerating}
            shareUrl={shareUrl}
            expiresAt={expiresAt}
            copied={copied}
            error={error}
            onCopy={handleCopyLink}
            onWhatsApp={shareViaWhatsApp}
            onTelegram={shareViaTelegram}
            onEmail={shareViaEmail}
            formatExpiryDate={formatExpiryDate}
          />
        </PopoverContent>
      </Popover>
    );
  }

  return (
    <Popover open={isOpen} onOpenChange={handleOpenPopover}>
      <PopoverTrigger asChild>
        <Button
          variant="outline"
          className="flex items-center gap-2 px-4 py-2 border-indigo-200 text-indigo-600 hover:bg-indigo-50 hover:border-indigo-300"
        >
          <Link2 className="w-4 h-4" />
          Get Shareable Link
        </Button>
      </PopoverTrigger>
      <PopoverContent className="w-80 p-4" align="end">
        <ShareableLinkContent
          isGenerating={isGenerating}
          shareUrl={shareUrl}
          expiresAt={expiresAt}
          copied={copied}
          error={error}
          onCopy={handleCopyLink}
          onWhatsApp={shareViaWhatsApp}
          onTelegram={shareViaTelegram}
          onEmail={shareViaEmail}
          formatExpiryDate={formatExpiryDate}
        />
      </PopoverContent>
    </Popover>
  );
}

interface ShareableLinkContentProps {
  isGenerating: boolean;
  shareUrl: string | null;
  expiresAt: string | null;
  copied: boolean;
  error: string | null;
  onCopy: () => void;
  onWhatsApp: () => void;
  onTelegram: () => void;
  onEmail: () => void;
  formatExpiryDate: (date: string) => string;
}

function ShareableLinkContent({
  isGenerating,
  shareUrl,
  expiresAt,
  copied,
  error,
  onCopy,
  onWhatsApp,
  onTelegram,
  onEmail,
  formatExpiryDate,
}: ShareableLinkContentProps) {
  if (isGenerating) {
    return (
      <div className="flex flex-col items-center justify-center py-6 gap-3">
        <Loader2 className="w-6 h-6 text-indigo-500 animate-spin" />
        <p className="text-sm text-slate-500">Generating shareable link...</p>
      </div>
    );
  }

  if (error) {
    return (
      <div className="py-4 text-center">
        <p className="text-sm text-red-600 mb-3">❌ {error}</p>
        <p className="text-xs text-slate-400">Please try again later</p>
      </div>
    );
  }

  if (!shareUrl) {
    return (
      <div className="py-4 text-center">
        <p className="text-sm text-slate-500">Preparing link...</p>
      </div>
    );
  }

  return (
    <div className="space-y-4">
      <div>
        <h4 className="font-semibold text-slate-900 text-sm mb-1">Shareable Link</h4>
        <p className="text-xs text-slate-400 mb-3">
          Anyone with this link can view the report
        </p>

        {/* Link Display */}
        <div className="flex items-center gap-2">
          <div className="flex-1 px-3 py-2 bg-slate-100 rounded-lg text-xs text-slate-600 truncate font-mono">
            {shareUrl}
          </div>
          <button
            onClick={onCopy}
            className={`p-2 rounded-lg transition-colors ${copied
                ? "bg-emerald-100 text-emerald-600"
                : "bg-slate-100 text-slate-600 hover:bg-slate-200"
              }`}
            title={copied ? "Copied!" : "Copy link"}
          >
            {copied ? (
              <Check className="w-4 h-4" />
            ) : (
              <Copy className="w-4 h-4" />
            )}
          </button>
        </div>

        {/* Expiry Notice */}
        {expiresAt && (
          <p className="text-xs text-amber-600 mt-2 flex items-center gap-1">
            ⏰ Expires on {formatExpiryDate(expiresAt)}
          </p>
        )}
      </div>

      {/* Share Options */}
      <div className="border-t pt-3">
        <p className="text-xs font-medium text-slate-400 uppercase tracking-wider mb-2">
          Share via
        </p>
        <div className="grid grid-cols-3 gap-2">
          <button
            onClick={onWhatsApp}
            className="flex flex-col items-center gap-1 p-2 rounded-lg bg-green-50 hover:bg-green-100 transition-colors"
          >
            <MessageCircle className="w-5 h-5 text-green-600" />
            <span className="text-[10px] text-slate-600">WhatsApp</span>
          </button>
          <button
            onClick={onTelegram}
            className="flex flex-col items-center gap-1 p-2 rounded-lg bg-blue-50 hover:bg-blue-100 transition-colors"
          >
            <Send className="w-5 h-5 text-blue-500" />
            <span className="text-[10px] text-slate-600">Telegram</span>
          </button>
          <button
            onClick={onEmail}
            className="flex flex-col items-center gap-1 p-2 rounded-lg bg-slate-100 hover:bg-slate-200 transition-colors"
          >
            <Mail className="w-5 h-5 text-slate-600" />
            <span className="text-[10px] text-slate-600">Email</span>
          </button>
        </div>
      </div>

      {/* Open in New Tab */}
      <a
        href={shareUrl}
        target="_blank"
        rel="noopener noreferrer"
        className="flex items-center justify-center gap-2 w-full py-2 text-sm font-medium text-indigo-600 hover:text-indigo-700 hover:bg-indigo-50 rounded-lg transition-colors"
      >
        <ExternalLink className="w-4 h-4" />
        Open in new tab
      </a>
    </div>
  );
}
